export type ValidEventValue =
  | "product.created"
  | "product.updated"
  | "product.deleted"
  | "order.created"
  | "order.paid"
  | "order.updated"
  | "order.refunded"
  | "order.fulfilled"
  | "order.upsell"
  | "order.chargeback"
  | "abandoned.created"
  | "subscription.created"
  | "subscription.cancelled";

export type ValidEventObject = {
  event: ValidEventValue;
};

type Domain = {
  id: number;
  apex: number;
  name: string;
  status: string;
  shop_id: number;
  created_at: string;
  is_primary: number;
  last_check: null | string;
  updated_at: string;
  cloudflare_id: null | string;
  cloudflare_path: null | string;
  certificate_path: null | string;
  cloudflare_ssl_id: null | string;
  additional_domains: null | string;
  cloudflare_content: null | string;
  cloudflare_ssl_path: null | string;
  stripe_validated_at: string;
  cloudflare_ssl_content: null | string;
  certificate_expiry_date: null | string;
  stripe_eur_validated_at: string;
  stripe_payment_method_domain: string;
  stripe_eur_payment_method_domain: string;
  additional_certificate_expiry_date: null | string;
};

type ShopInfo = {
  id: number;
  name: string;
  slug: string;
  country: string;
  country_code: string;
  timezone: string;
  website: null | string;
  monthly_revenue: null | string;
  status: number;
  enable_draft_upsell: number;
  redirection_enable: string;
  redirection_url: null | string;
  term_and_services: number;
  term_accept_url: null | string;
  password_page_message: null | string;
  partner_expired_at: null | string;
  partner_started_at: null | string;
  scheduled_block_at: null | string;
  pix_attempts: number;
  sms_provider: null | string;
  is_global_market: number;
  default_shipping_created: number;
  title: null | string;
  sentry: number;
  permanent_domain: string;
  settings_general: {
    id: number;
    shop_id: number;
    business_name: string;
    full_name: string;
    call_center_phonecode: null | string;
    call_center_phone: null | string;
    address1: string;
    address2: null | string;
    number: string;
    neighbourhood: string;
    city: string;
    country: string;
    state: string;
    zip: string;
    app_for: null | string;
    order_prefix: string;
    order_suffix: string;
    number_of_days: number;
    is_cancel_boleto_active: number;
    cancel_boleto_active_at: string;
    number_of_days_pix: number;
    is_cancel_pix_active: number;
    cancel_pix_active_at: null | string;
    created_at: string;
    updated_at: string;
    stripe_mode: number;
    multi_currency: string;
    base_currency: string;
    currency: string;
    currency_symbol: string;
    html_with_currency: string;
    html_without_currency: string;
    email_with_currency: string;
    email_without_currency: string;
    comma_as_decimal: number;
    weight_unit: string;
    preferred_language: string;
    domain_id: null | string;
    domain_authentication: number;
    cc_token_enabled: number;
    is_fiscal: number;
    multi_currency_sales: number;
    call_center_countrycode: null | string;
  };
};

type Payment = {
  id: number;
  type: string;
  amount: number;
  pix_qr: null | string;
  cc_name: string;
  gateway: string;
  cc_brand: string;
  order_id: number;
  pix_code: null | string;
  split_fee: number;
  status_id: number;
  birth_date: null | string;
  created_at: string;
  expir_year: string;
  konduto_id: string;
  updated_at: string;
  boleto_code: string;
  boleto_link: string;
  captured_at: string;
  card_number: string;
  expir_month: string;
  refunded_at: null | string;
  afillio_code: null | string;
  cancelled_at: null | string;
  cc_first_six: string;
  cc_last_four: string;
  clearsale_id: string;
  payment_type: string;
  release_date: null | string;
  cc_first_four: string;
  mp_payment_id: null | string;
  security_code: number;
  balance_status: null | string;
  boleto_barcode: string;
  pix_limit_date: null | string;
  charged_back_at: null | string;
  last_plug_check: null | string;
  rede_payment_id: null | string;
  soft_descriptor: null | string;
  zoop_payment_id: string;
  actual_status_id: number;
  cielo_payment_id: null | string;
  customer_card_id: null | string;
  ebanx_payment_id: null | string;
  actual_price_paid: number;
  appmax_payment_id: string;
  authorization_nsu: null | string;
  boleto_limit_date: string;
  installments_rate: null | string;
  last_sync_oktapay: null | string;
  authorization_code: null | string;
  cartx_split_amount: number;
  gateway_payment_id: string;
  hubsale_payment_id: string;
  installments_price: null | string;
  no_of_installments: null | string;
  actual_exchange_rate: number;
  clearsale_last_check: null | string;
  pagseguro_payment_id: string;
  actual_price_paid_currency: string;
  chargedback_refunded_synced_at: null | string;
};

type Customer = {
  id: number;
  cpf: string;
  cpn: string;
  cnpj: string;
  tags: null | string;
  email: string;
  notes: string;
  phone: string;
  source: string;
  shop_id: number;
  full_name: string;
  last_name: string;
  created_at: string;
  first_name: string;
  tax_exempt: number;
  updated_at: string;
  session_key: null | string;
  house_number: string;
  state_reg_num: null | string;
  email_marketing: number;
  paypal_payer_id: null | string;
  phone_marketing: number;
  cartpanda_pay_at: null | string;
  global_customer_id: null | string;
  cartpanda_pay_customer_id: null | string;
};

type Webhook = {
  id: number;
  endpoint: string;
  shop_id: number;
  product_variants: {
    [key: string]: unknown;
  }[];
};

export type OrderCreatedWebhook = {
  event: string;
  order: {
    id: number;
    shop_id: number;
    customer_id: number;
    user_id: number;
    location_id: number;
    dsers_batch_id: null | string;
    processed_in_dsers: null | string;
    tiny_erp_id: null | string;
    test: number;
    shipping_lines: string;
    name: string;
    subtotal_price: number;
    subtotal_price_set: number;
    total_discounts: number;
    total_discounts_set: number;
    total_line_items_price: number;
    total_line_items_price_set: number;
    total_price: number;
    total_price_set: number;
    total_tax: number;
    total_tax_set: number;
    total_tip_received: number;
    total_weight: number;
    no_of_installments: number;
    installments_rate: number;
    order_status_url: string;
    email: string;
    legal_entity: string;
    is_archived: number;
    billing_address_id: number;
    shipping_address_id: number;
    browser_ip: string;
    buyer_accepts_marketing: number;
    buyer_accepts_phone_marketing: number;
    cancel_reason: string;
    cart_token: string;
    client_details: string;
    currency: string;
    customer_locale: string;
    discount_applications: string;
    discount_codes: string;
    landing_site: string;
    note: string;
    note_attributes: string;
    custom_notes: string;
    number: number;
    order_number: string;
    payment_details: null | string;
    payment_gateway_names: null | string;
    phone: string;
    presentment_currency: string;
    processing_method: string;
    referring_site: string;
    source_name: string;
    tags: null | string;
    tax_lines: number;
    taxes_included: number;
    token: string;
    card_token: string;
    customer_token: string;
    cvv: string;
    is_sync: number;
    in_progress: number;
    is_woocommerce_sync: number;
    is_magento_sync: number;
    status_id: string;
    fulfillment_status: string;
    chargeback_received: number;
    processed_at: string;
    cancelled_at: null | string;
    closed_at: null | string;
    boleto_email_sent: number;
    cartxpayment_transaction_id: string;
    created_at: string;
    updated_at: string;
    order_comment: null | string;
    is_cartx_test: number;
    paypal_order_id: string;
    temp_paypal: number;
    pagseguro_ccCPF: string;
    antifraud_synced_at: null | string;
    user_agent: string;
    is_cp_pay: string;
    payment_gateway_token: null | string;
    payment_status: number;
    appmax_payment_token: string;
    payment_gateway: string;
    boleto_code: string;
    boleto_link: string;
    boleto_limit_date: string;
    pix_code: null | string;
    pix_qr: null | string;
    pix_limit_date: null | string;
    payment_type: string;
    tracking_number: null | string;
    tracking_numbers: string;
    afid: null | string;
    affiliate_amount: null | string;
    affiliate_slug: null | string;
    coproducer_amount: null | string;
    coproducer_slug: null | string;
    shopify_order_id: number;
    thank_you_page: string;
    total_price_without_tax: number;
    address: null | string;
    line_items: {
      id: number;
      order_id: number;
      product_id: number;
      variant_id: number;
      fulfillable_quantity: number;
      fulfillment_service: string;
      grams: number;
      price: number;
      quantity: number;
      inventory_sync: number;
      requires_shipping: number;
      sku: string;
      title: string;
      variant_title: string;
      vendor: string;
      name: string;
      gift_card: number;
      taxable: number;
      total_discount: number;
      total_discount_set: number;
      discount_allocations: number;
      shipping_method: null | string;
      total_cost_of_order: null | string;
      aliexpress_order_number: null | string;
      tracking_no: null | string;
      status_id: number;
      is_ocu: number;
      page_id: number;
      custom_options: null | string;
      is_digital: number;
      up_sell_id: number;
      up_sell_type: null | string;
      offer_id: string;
      refunded_quantity: number;
      is_refunded: number;
      kit_id: number;
      is_kit: number;
      created_at: string;
      updated_at: string;
      appointment_data: null | string;
      app_type: number;
      app_type_id: null | string;
      gift_code: null | string;
      formatted_custom_options: boolean;
    }[];
    customer: Customer;
    orders_shippings: null | string;
    fulfillments: {
      id: number;
      order_id: number;
      shop_id: number;
      status_id: number;
      name: string;
      notify_customer: number;
      receipt: null | string;
      service: string;
      shipment_status: string;
      tracking_company: string;
      tracking_number: null | string;
      tracking_numbers: string;
      tracking_url: null | string;
      tracking_urls: string;
      invoice_key: null | string;
      variant_inventory_management: string;
      created_at: string;
      updated_at: string;
      number: number;
      melhor_envio_id: null | string;
    }[];
    shop: ShopInfo;
    all_payments: {
      authorizationCode: string;
      gateway: string;
      type: string;
      seller_split_amount: number;
      cartpanda_pay_split_amount: number;
      actual_price_paid_currency: string;
      actual_price_paid: number;
      actual_exchange_rate: number;
    }[];
    payment: Payment;
  };
  webhook: Webhook;
};

export type OrderPaidWebhook = {
  event: string;
  order: {
    id: number;
    cvv: string;
    afid: null | string;
    name: string;
    note: string;
    shop: ShopInfo;
    tags: null | string;
    test: number;
    email: string;
    phone: string;
    token: string;
    number: number;
    pix_qr: null | string;
    address: null | string;
    is_sync: number;
    payment: Payment;
    shop_id: number;
    user_id: number;
    currency: string;
    customer: Customer;
    pix_code: null | string;
    closed_at: null | string;
    is_cp_pay: string;
    shop_info: ShopInfo;
    status_id: string;
    tax_lines: number;
    total_tax: number;
    browser_ip: string;
    card_token: string;
    cart_token: string;
    created_at: string;
    line_items: {
      id: number;
      sku: string;
      name: string;
      grams: number;
      price: number;
      title: string;
      is_kit: number;
      is_ocu: number;
      kit_id: number;
      vendor: string;
      page_id: number;
      taxable: number;
      variant: {
        id: number;
        sku: null | string;
        price: number;
        title: string;
        width: string;
        height: string;
        length: string;
        weight: null | string;
        barcode: null | string;
        default: number;
        taxable: number;
        position: number;
        quantity: number;
        swatches: null | string;
        created_at: string;
        deleted_at: null | string;
        product_id: number;
        updated_at: string;
        weight_unit: null | string;
        cost_per_item: number;
        aliexpress_sku: null | string;
        dimension_unit: null | string;
        compare_at_price: number;
        inventory_policy: number;
        requires_shipping: number;
        show_to_affiliate: number;
        has_digital_attachment: number;
        enabled_shopify_redirect: number;
        prevent_out_of_stock_selling: number;
      };
      app_type: number;
      offer_id: string;
      order_id: number;
      quantity: number;
      gift_card: number;
      gift_code: null | string;
      status_id: number;
      created_at: string;
      is_digital: number;
      product_id: number;
      up_sell_id: number;
      updated_at: string;
      variant_id: number;
      app_type_id: null | string;
      is_refunded: number;
      tracking_no: null | string;
      up_sell_type: null | string;
      variant_title: string;
      custom_options: null | string;
      inventory_sync: number;
      total_discount: number;
      shipping_method: null | string;
      appointment_data: null | string;
      refunded_quantity: number;
      requires_shipping: number;
    }[];
    updated_at: string;
    user_agent: string;
    boleto_code: string;
    boleto_link: string;
    customer_id: number;
    in_progress: number;
    is_archived: number;
    location_id: number;
    source_name: string;
    temp_paypal: number;
    tiny_erp_id: null | string;
    total_price: number;
    all_payments: {
      type: string;
      gateway: string;
      actual_price_paid: number;
      authorizationCode: string;
      seller_split_amount: number;
      actual_exchange_rate: number;
      actual_price_paid_currency: string;
      cartpanda_pay_split_amount: number;
    }[];
    cancelled_at: null | string;
    custom_notes: string;
    fulfillments: {
      id: number;
      name: string;
      number: number;
      receipt: null | string;
      service: string;
      shop_id: number;
      order_id: number;
      status_id: number;
      created_at: string;
      updated_at: string;
      invoice_key: null | string;
      tracking_url: null | string;
      tracking_urls: string;
      melhor_envio_id: null | string;
      notify_customer: number;
      shipment_status: string;
      tracking_number: null | string;
      tracking_company: string;
      tracking_numbers: string;
      variant_inventory_management: string;
    }[];
    landing_site: string;
    legal_entity: string;
    order_number: string;
    payment_type: string;
    processed_at: string;
    total_weight: number;
    transactions: {
      type: string;
      gateway: string;
      actual_price_paid: number;
      authorizationCode: string;
      seller_split_amount: number;
      actual_exchange_rate: number;
      actual_price_paid_currency: string;
      cartpanda_pay_split_amount: number;
    }[];
    cancel_reason: string;
    checkout_link: string;
    is_cartx_test: number;
    order_comment: null | string;
    total_tax_set: number;
    affiliate_slug: null | string;
    client_details: string;
    customer_token: string;
    discount_codes: string;
    dsers_batch_id: null | string;
    payment_status: number;
    pix_limit_date: null | string;
    referring_site: string;
    shipping_lines: string;
    subtotal_price: number;
    taxes_included: number;
    thank_you_page: string;
    coproducer_slug: null | string;
    customer_locale: string;
    is_magento_sync: number;
    note_attributes: string;
    pagseguro_ccCPF: string;
    payment_details: null | string;
    payment_gateway: string;
    paypal_order_id: string;
    total_discounts: number;
    total_price_set: number;
    tracking_number: null | string;
    affiliate_amount: null | string;
    order_status_url: string;
    orders_shippings: null | string;
    shopify_order_id: number;
    tracking_numbers: string;
    boleto_email_sent: number;
    boleto_limit_date: string;
    coproducer_amount: null | string;
    installments_rate: number;
    processing_method: string;
    billing_address_id: number;
    digital_attachment: string;
    fulfillment_status: string;
    no_of_installments: number;
    processed_in_dsers: null | string;
    subtotal_price_set: number;
    total_tip_received: number;
    antifraud_synced_at: null | string;
    chargeback_received: number;
    is_woocommerce_sync: number;
    shipping_address_id: number;
    total_discounts_set: number;
    tracking_parameters: {
      [key: string]: unknown;
    }[];
    appmax_payment_token: string;
    presentment_currency: string;
    discount_applications: string;
    payment_gateway_names: null | string;
    payment_gateway_token: null | string;
    total_line_items_price: number;
    buyer_accepts_marketing: number;
    total_price_without_tax: number;
    total_line_items_price_set: number;
    cartxpayment_transaction_id: string;
    buyer_accepts_phone_marketing: number;
    local_currency_amount_without_tax: string;
  };
  webhook: Webhook;
};

export type OrderRefundedWebhook = {
  event: string;
  order: {
    id: number;
    cvv: string;
    afid: string;
    name: string;
    note: string;
    shop: {
      id: number;
      name: string;
      slug: string;
      phone: string;
      title: string;
      sentry: number;
      status: number;
      country: string;
      website: null | string;
      owner_id: number;
      timezone: string;
      phone_ext: string;
      created_at: string;
      deleted_at: null | string;
      updated_at: string;
      block_script: number;
      country_code: string;
      enable_store: number;
      pix_attempts: number;
      platform_for: string;
      sms_provider: string;
      send_address2: number;
      created_at_temp: null | string;
      monthly_revenue: null | string;
      oktapay_enabled: number;
      operations_type: null | string;
      password_enable: string;
      redirection_url: null | string;
      term_accept_url: null | string;
      current_platform: null | string;
      is_global_market: number;
      min_cart_quantity: number;
      onboarding_status: number;
      revenue_per_month: null | string;
      term_and_services: number;
      cartxpayments_mode: string;
      partner_expired_at: null | string;
      partner_started_at: null | string;
      redirection_enable: string;
      scheduled_block_at: null | string;
      enable_draft_upsell: number;
      pagseguro_v4_enabled: number;
      scheduled_deleted_at: string;
      password_page_message: string;
      wrong_order_email_count: number;
      default_shipping_created: number;
      settings_general: {
        id: number;
        cpf: string;
        zip: string;
        city: string;
        cnpj: string;
        phone: string;
        state: string;
        number: string;
        app_for: null | string;
        country: string;
        shop_id: number;
        address1: string;
        address2: null | string;
        currency: string;
        domain_id: number;
        full_name: string;
        is_fiscal: number;
        created_at: string;
        updated_at: string;
        store_email: string;
        stripe_mode: number;
        weight_unit: string;
        order_prefix: string;
        order_suffix: string;
        base_currency: string;
        business_name: string;
        neighbourhood: string;
        customer_email: string;
        multi_currency: string;
        number_of_days: number;
        currency_symbol: string;
        cc_token_enabled: number;
        comma_as_decimal: number;
        call_center_phone: string;
        html_with_currency: string;
        number_of_days_pix: number;
        preferred_language: string;
        email_with_currency: string;
        cancel_pix_active_at: null | string;
        is_cancel_pix_active: number;
        multi_currency_sales: number;
        call_center_phonecode: string;
        domain_authentication: number;
        html_without_currency: string;
        email_without_currency: string;
        call_center_countrycode: string;
        cancel_boleto_active_at: null | string;
        is_cancel_boleto_active: number;
      };
    };
    tags: null | string;
    test: number;
    email: string;
    phone: string;
    token: string;
    number: number;
    address: {
      id: number;
      zip: string;
      city: string;
      name: string;
      type: string;
      phone: string;
      address: string;
      company: string;
      country: string;
      address1: string;
      address2: string;
      house_no: string;
      latitude: string;
      order_id: number;
      province: string;
      last_name: string;
      longitude: string;
      created_at: string;
      first_name: string;
      updated_at: string;
      compartment: string;
      country_code: string;
      neighborhood: string;
      province_code: string;
    };
    is_sync: number;
    payment: {
      id: number;
      type: string;
      amount: number;
      pix_qr: null | string;
      cc_name: string;
      gateway: string;
      cc_brand: string;
      order_id: number;
      pix_code: null | string;
      split_fee: number;
      status_id: number;
      birth_date: null | string;
      created_at: string;
      expir_year: string;
      konduto_id: string;
      updated_at: string;
      boleto_code: string;
      boleto_link: string;
      captured_at: string;
      card_number: string;
      expir_month: string;
      refunded_at: null | string;
      afillio_code: string;
      cancelled_at: null | string;
      cc_first_six: string;
      cc_last_four: string;
      clearsale_id: string;
      payment_type: string;
      release_date: null | string;
      cc_first_four: string;
      mp_payment_id: null | string;
      security_code: number;
      balance_status: null | string;
      boleto_barcode: string;
      pix_limit_date: null | string;
      charged_back_at: null | string;
      last_plug_check: null | string;
      rede_payment_id: null | string;
      soft_descriptor: null | string;
      zoop_payment_id: string;
      actual_status_id: number;
      cielo_payment_id: null | string;
      customer_card_id: null | string;
      ebanx_payment_id: null | string;
      actual_price_paid: number;
      appmax_payment_id: string;
      authorization_nsu: string;
      boleto_limit_date: string;
      installments_rate: null | string;
      last_sync_oktapay: null | string;
      authorization_code: null | string;
      cartx_split_amount: number;
      gateway_payment_id: string;
      hubsale_payment_id: string;
      installments_price: null | string;
      no_of_installments: null | string;
      seller_split_amount: number;
      actual_exchange_rate: number;
      clearsale_last_check: null | string;
      pagseguro_payment_id: null | string;
      actual_price_paid_currency: string;
      cartpanda_pay_split_amount: number;
      chargedback_refunded_synced_at: null | string;
    };
    refunds: {
      id: number;
      note: string;
      order_id: number;
      status_id: number;
      sub_total: number;
      created_at: string;
      updated_at: string;
      total_amount: number;
    }[];
    shop_id: number;
    user_id: number;
    currency: string;
    customer: {
      id: number;
      cpf: string;
      cpn: string;
      cnpj: string;
      tags: string[];
      email: string;
      notes: string;
      phone: string;
      source: string;
      shop_id: number;
      full_name: string;
      last_name: string;
      created_at: string;
      first_name: string;
      tax_exempt: number;
      updated_at: string;
      session_key: null | string;
      house_number: string;
      state_reg_num: null | string;
      email_marketing: number;
      paypal_payer_id: null | string;
      phone_marketing: number;
      cartpanda_pay_at: null | string;
      global_customer_id: number;
      accepts_email_marketing: string;
      cartpanda_pay_customer_id: null | string;
      human_readable_created_at: string;
    };
    pix_code: null | string;
    closed_at: null | string;
    is_cp_pay: string;
    public_id: string;
    shop_info: {
      id: number;
      name: string;
      slug: string;
      phone: string;
      title: string;
      sentry: number;
      status: number;
      country: string;
      website: null | string;
      owner_id: number;
      timezone: string;
      phone_ext: string;
      created_at: string;
      deleted_at: null | string;
      updated_at: string;
      block_script: number;
      country_code: string;
      enable_store: number;
      pix_attempts: number;
      platform_for: string;
      sms_provider: string;
      send_address2: number;
      created_at_temp: null | string;
      monthly_revenue: null | string;
      oktapay_enabled: number;
      operations_type: null | string;
      password_enable: string;
      redirection_url: null | string;
      term_accept_url: null | string;
      current_platform: null | string;
      is_global_market: number;
      settings_general: {
        id: number;
        cpf: string;
        zip: string;
        city: string;
        cnpj: string;
        phone: string;
        state: string;
        number: string;
        app_for: null | string;
        country: string;
        shop_id: number;
        address1: string;
        address2: null | string;
        currency: string;
        domain_id: number;
        full_name: string;
        is_fiscal: number;
        created_at: string;
        updated_at: string;
        store_email: string;
        stripe_mode: number;
        weight_unit: string;
        order_prefix: string;
        order_suffix: string;
        base_currency: string;
        business_name: string;
        neighbourhood: string;
        customer_email: string;
        multi_currency: string;
        number_of_days: number;
        currency_symbol: string;
        cc_token_enabled: number;
        comma_as_decimal: number;
        call_center_phone: string;
        html_with_currency: string;
        number_of_days_pix: number;
        preferred_language: string;
        email_with_currency: string;
        cancel_pix_active_at: null | string;
        is_cancel_pix_active: number;
        multi_currency_sales: number;
        call_center_phonecode: string;
        domain_authentication: number;
        html_without_currency: string;
        email_without_currency: string;
        call_center_countrycode: string;
        cancel_boleto_active_at: null | string;
        is_cancel_boleto_active: number;
      };
    };
    status_id: string;
    tax_lines: number;
    total_tax: string;
    browser_ip: string;
    card_token: string;
    cart_token: string;
    created_at: string;
    line_items: {
      id: number;
      sku: string;
      name: string;
      grams: number;
      price: number;
      title: string;
      is_kit: number;
      is_ocu: number;
      kit_id: number;
      vendor: string;
      page_id: number;
      taxable: number;
      variant: {
        id: number;
        sku: string;
        price: string;
        title: string;
        width: string;
        height: string;
        length: string;
        weight: number;
        barcode: null | string;
        default: number;
        taxable: number;
        image_id: string;
        position: number;
        quantity: number;
        swatches: null | string;
        created_at: string;
        deleted_at: null | string;
        nimble_sku: string;
        product_id: number;
        updated_at: string;
        weight_unit: string;
        mobile_price: number;
        cost_per_item: string;
        variant_image: {
          [key: string]: unknown;
        }[];
        aliexpress_sku: null | string;
        dimension_unit: string;
        compare_at_price: string;
        inventory_policy: number;
        requires_shipping: number;
        show_to_affiliate: number;
        has_digital_attachment: number;
        enabled_shopify_redirect: number;
        prevent_out_of_stock_selling: number;
      };
      app_type: number;
      offer_id: string;
      order_id: number;
      quantity: number;
      gift_card: number;
      gift_code: null | string;
      status_id: number;
      created_at: string;
      is_digital: number;
      product_id: number;
      up_sell_id: number;
      updated_at: string;
      variant_id: number;
      app_type_id: null | string;
      is_refunded: number;
      tracking_no: null | string;
      up_sell_type: null | string;
      variant_title: string;
      custom_options: null | string;
      inventory_sync: number;
      total_discount: number;
      shipping_method: null | string;
      appointment_data: null | string;
      refunded_quantity: number;
      requires_shipping: number;
      product_main_image: {
        id: number;
        alt: string;
        src: string;
        url: string;
        width: number;
        height: number;
        position: number;
        created_at: string;
        media_type: string;
        product_id: number;
        updated_at: string;
        aspect_ratio: string;
      };
      total_discount_set: number;
      fulfillment_service: string;
      product_images_info: null | string;
      total_cost_of_order: null | string;
      discount_allocations: number;
      fulfillable_quantity: number;
      aliexpress_order_number: null | string;
      formatted_custom_options: boolean;
    }[];
    updated_at: string;
    user_agent: string;
    boleto_code: string;
    boleto_link: string;
    customer_id: number;
    in_progress: number;
    is_archived: number;
    location_id: number;
    source_name: string;
    temp_paypal: number;
    tiny_erp_id: number;
    total_price: string;
    all_payments: {
      type: string;
      gateway: string;
      actual_price_paid: number;
      authorizationCode: string;
      seller_split_amount: number;
      actual_exchange_rate: number;
      actual_price_paid_currency: string;
      cartpanda_pay_split_amount: number;
    }[];
    cancelled_at: null | string;
    custom_notes: string;
    fulfillments: {
      [key: string]: unknown;
    }[];
    landing_site: string;
    legal_entity: string;
    order_number: string;
    payment_type: string;
    processed_at: string;
    total_weight: number;
    transactions: {
      type: string;
      gateway: string;
      actual_price_paid: number;
      authorizationCode: string;
      seller_split_amount: number;
      actual_exchange_rate: number;
      actual_price_paid_currency: string;
      cartpanda_pay_split_amount: number;
    }[];
    cancel_reason: string;
    is_cartx_test: number;
    order_comment: null | string;
    shop_currency: string;
    total_tax_set: string;
    affiliate_slug: string;
    client_details: string;
    customer_token: string;
    discount_codes: string;
    dsers_batch_id: null | string;
    payment_status: number;
    pix_limit_date: null | string;
    referring_site: string;
    shipping_lines: string;
    subtotal_price: string;
    taxes_included: number;
    thank_you_page: string;
    coproducer_slug: null | string;
    customer_locale: string;
    is_magento_sync: number;
    note_attributes: string;
    pagseguro_ccCPF: string;
    payment_details: string;
    payment_gateway: string;
    paypal_order_id: null | string;
    total_discounts: string;
    total_price_set: string;
    tracking_number: null | string;
    affiliate_amount: string;
    order_status_url: string;
    orders_shippings: {
      id: number;
      code: string;
      price: number;
      title: string;
      source: string;
      shop_id: number;
      order_id: number;
      label_url: null | string;
      created_at: string;
      updated_at: string;
      is_refunded: number;
      mobile_price: string;
      frenet_service: null | string;
      mandae_service: null | string;
      paid_by_client: number;
      mandae_order_id: null | string;
      melhor_envio_id: null | string;
      discounted_price: number;
      shipping_gateway: string;
      actual_price_paid: number;
      delivery_category: string;
      carrier_identifier: string;
      intelipost_service: null | string;
      melhor_envio_service: null | string;
      correios_shipping_method_code: null | string;
      requested_fulfillment_service_id: string;
    };
    payment_currency: string;
    shopify_order_id: number;
    tracking_numbers: null | string;
    boleto_email_sent: number;
    boleto_limit_date: string;
    coproducer_amount: null | string;
    installments_rate: number;
    processing_method: string;
    billing_address_id: number;
    digital_attachment: string;
    fulfillment_status: string;
    no_of_installments: number;
    processed_in_dsers: null | string;
    subtotal_price_set: string;
    total_tip_received: string;
    antifraud_synced_at: null | string;
    chargeback_received: number;
    is_woocommerce_sync: number;
    shipping_address_id: number;
    total_discounts_set: string;
    tracking_parameters: {
      [key: string]: unknown;
    }[];
    appmax_payment_token: string;
    formatted_created_at: string;
    presentment_currency: string;
    converted_total_price: string;
    discount_applications: string;
    payment_gateway_names: null | string;
    payment_gateway_token: null | string;
    total_line_items_price: string;
    buyer_accepts_marketing: number;
    total_price_without_tax: string;
    unformatted_total_price: number;
    total_line_items_price_set: string;
    cartxpayment_transaction_id: string;
    buyer_accepts_phone_marketing: number;
    local_currency_amount_without_tax: string;
    unformatted_total_price_without_tax: number;
  };
  webhook: Webhook;
};
